/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiContentRouteImport } from './routes/api/content'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminDestinationsRouteImport } from './routes/admin/destinations'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'
import { Route as AdminBikesRouteImport } from './routes/admin/bikes'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin/settings'
import { Route as ApiAdminPackagesRouteImport } from './routes/api/admin/packages'
import { Route as ApiAdminInquiriesRouteImport } from './routes/api/admin/inquiries'
import { Route as ApiAdminDestinationsRouteImport } from './routes/api/admin/destinations'
import { Route as ApiAdminBlogsRouteImport } from './routes/api/admin/blogs'
import { Route as ApiAdminBikesRouteImport } from './routes/api/admin/bikes'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiContentRoute = ApiContentRouteImport.update({
  id: '/api/content',
  path: '/api/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDestinationsRoute = AdminDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBikesRoute = AdminBikesRouteImport.update({
  id: '/bikes',
  path: '/bikes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPackagesRoute = ApiAdminPackagesRouteImport.update({
  id: '/api/admin/packages',
  path: '/api/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInquiriesRoute = ApiAdminInquiriesRouteImport.update({
  id: '/api/admin/inquiries',
  path: '/api/admin/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDestinationsRoute = ApiAdminDestinationsRouteImport.update({
  id: '/api/admin/destinations',
  path: '/api/admin/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBlogsRoute = ApiAdminBlogsRouteImport.update({
  id: '/api/admin/blogs',
  path: '/api/admin/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBikesRoute = ApiAdminBikesRouteImport.update({
  id: '/api/admin/bikes',
  path: '/api/admin/bikes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/bikes': typeof AdminBikesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/content': typeof ApiContentRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/bikes': typeof ApiAdminBikesRoute
  '/api/admin/blogs': typeof ApiAdminBlogsRoute
  '/api/admin/destinations': typeof ApiAdminDestinationsRoute
  '/api/admin/inquiries': typeof ApiAdminInquiriesRoute
  '/api/admin/packages': typeof ApiAdminPackagesRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/bikes': typeof AdminBikesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/content': typeof ApiContentRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/bikes': typeof ApiAdminBikesRoute
  '/api/admin/blogs': typeof ApiAdminBlogsRoute
  '/api/admin/destinations': typeof ApiAdminDestinationsRoute
  '/api/admin/inquiries': typeof ApiAdminInquiriesRoute
  '/api/admin/packages': typeof ApiAdminPackagesRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/bikes': typeof AdminBikesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/content': typeof ApiContentRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/bikes': typeof ApiAdminBikesRoute
  '/api/admin/blogs': typeof ApiAdminBlogsRoute
  '/api/admin/destinations': typeof ApiAdminDestinationsRoute
  '/api/admin/inquiries': typeof ApiAdminInquiriesRoute
  '/api/admin/packages': typeof ApiAdminPackagesRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/bikes'
    | '/admin/blogs'
    | '/admin/destinations'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/api/contact'
    | '/api/content'
    | '/admin/'
    | '/api/admin/bikes'
    | '/api/admin/blogs'
    | '/api/admin/destinations'
    | '/api/admin/inquiries'
    | '/api/admin/packages'
    | '/api/admin/settings'
    | '/api/admin/stats'
    | '/api/admin/upload'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/bikes'
    | '/admin/blogs'
    | '/admin/destinations'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/api/contact'
    | '/api/content'
    | '/admin'
    | '/api/admin/bikes'
    | '/api/admin/blogs'
    | '/api/admin/destinations'
    | '/api/admin/inquiries'
    | '/api/admin/packages'
    | '/api/admin/settings'
    | '/api/admin/stats'
    | '/api/admin/upload'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/bikes'
    | '/admin/blogs'
    | '/admin/destinations'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/api/contact'
    | '/api/content'
    | '/admin/'
    | '/api/admin/bikes'
    | '/api/admin/blogs'
    | '/api/admin/destinations'
    | '/api/admin/inquiries'
    | '/api/admin/packages'
    | '/api/admin/settings'
    | '/api/admin/stats'
    | '/api/admin/upload'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
  ApiContentRoute: typeof ApiContentRoute
  ApiAdminBikesRoute: typeof ApiAdminBikesRoute
  ApiAdminBlogsRoute: typeof ApiAdminBlogsRoute
  ApiAdminDestinationsRoute: typeof ApiAdminDestinationsRoute
  ApiAdminInquiriesRoute: typeof ApiAdminInquiriesRoute
  ApiAdminPackagesRoute: typeof ApiAdminPackagesRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/content': {
      id: '/api/content'
      path: '/api/content'
      fullPath: '/api/content'
      preLoaderRoute: typeof ApiContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/destinations': {
      id: '/admin/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminDestinationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bikes': {
      id: '/admin/bikes'
      path: '/bikes'
      fullPath: '/admin/bikes'
      preLoaderRoute: typeof AdminBikesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/packages': {
      id: '/api/admin/packages'
      path: '/api/admin/packages'
      fullPath: '/api/admin/packages'
      preLoaderRoute: typeof ApiAdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/inquiries': {
      id: '/api/admin/inquiries'
      path: '/api/admin/inquiries'
      fullPath: '/api/admin/inquiries'
      preLoaderRoute: typeof ApiAdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/destinations': {
      id: '/api/admin/destinations'
      path: '/api/admin/destinations'
      fullPath: '/api/admin/destinations'
      preLoaderRoute: typeof ApiAdminDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/blogs': {
      id: '/api/admin/blogs'
      path: '/api/admin/blogs'
      fullPath: '/api/admin/blogs'
      preLoaderRoute: typeof ApiAdminBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bikes': {
      id: '/api/admin/bikes'
      path: '/api/admin/bikes'
      fullPath: '/api/admin/bikes'
      preLoaderRoute: typeof ApiAdminBikesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBikesRoute: typeof AdminBikesRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminDestinationsRoute: typeof AdminDestinationsRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBikesRoute: AdminBikesRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminDestinationsRoute: AdminDestinationsRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
  ApiContentRoute: ApiContentRoute,
  ApiAdminBikesRoute: ApiAdminBikesRoute,
  ApiAdminBlogsRoute: ApiAdminBlogsRoute,
  ApiAdminDestinationsRoute: ApiAdminDestinationsRoute,
  ApiAdminInquiriesRoute: ApiAdminInquiriesRoute,
  ApiAdminPackagesRoute: ApiAdminPackagesRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
